version: "3"
services:
  gateway:
    image: vm2:443/gateway:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet


  aircraft:
    image: vm2:443/aircraft:0.1
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  crew:
    image: vm2:443/crew:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet: